name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.README }}
      - name: Commit & Push
        run: |
          git config user.name luail
          git config user.email kynia0506@naver.com
          git remote set-url origin https://github.com/luail/luail
          git add -A .
          git commit -m "generated"
          git push https://${GITHUB_TOKEN}@github.com/luail/luail.git

